CREATE DATABASE IF NOT EXISTS tuition_management CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE tuition_management;
CREATE TABLE users (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 username VARCHAR(100) NOT NULL UNIQUE,
 password_hash VARCHAR(255) NOT NULL,
 role ENUM('admin','teacher','student') NOT NULL,
 is_active BOOLEAN NOT NULL DEFAULT TRUE,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;


CREATE TABLE photo_assets (
 id VARCHAR(100) PRIMARY KEY,
 mime_type VARCHAR(50) NOT NULL,
 data MEDIUMBLOB NOT NULL,
 created_at DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE admins (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id BIGINT UNSIGNED NOT NULL UNIQUE,
 name VARCHAR(150) NOT NULL, email VARCHAR(255), phone VARCHAR(30),
 FOREIGN KEY(user_id) REFERENCES users(id)
) ENGINE=InnoDB;
CREATE TABLE teachers (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id BIGINT UNSIGNED NOT NULL UNIQUE,
 teacher_id VARCHAR(30) NOT NULL UNIQUE, name VARCHAR(150) NOT NULL, photo VARCHAR(500),
 gender VARCHAR(30), dob DATE, phone VARCHAR(30), email VARCHAR(255), address TEXT,
 qualification VARCHAR(255), experience VARCHAR(100), joining_date DATE,
 status ENUM('active','inactive') NOT NULL DEFAULT 'active',
 created_at DATETIME DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 FOREIGN KEY(user_id) REFERENCES users(id)
) ENGINE=InnoDB;
CREATE TABLE parents (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(150) NOT NULL,
 relationship VARCHAR(80), phone VARCHAR(30), email VARCHAR(255), address TEXT
) ENGINE=InnoDB;
CREATE TABLE students (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id BIGINT UNSIGNED NOT NULL UNIQUE,
 student_id VARCHAR(30) NOT NULL UNIQUE, name VARCHAR(150) NOT NULL, photo VARCHAR(500),
 gender VARCHAR(30), dob DATE, phone VARCHAR(30), address TEXT, school_name VARCHAR(255),
 admission_date DATE, status ENUM('active','inactive') NOT NULL DEFAULT 'active',
 parent_id BIGINT UNSIGNED, FOREIGN KEY(user_id) REFERENCES users(id),
 FOREIGN KEY(parent_id) REFERENCES parents(id) ON DELETE SET NULL
) ENGINE=InnoDB;
CREATE TABLE subjects (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(100) NOT NULL UNIQUE, is_active BOOLEAN NOT NULL DEFAULT TRUE
) ENGINE=InnoDB;
CREATE TABLE classes (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, class_name VARCHAR(100) NOT NULL, batch VARCHAR(100) NOT NULL,
 subject_id BIGINT UNSIGNED NOT NULL, room VARCHAR(100), max_students INT NOT NULL DEFAULT 30,
 status ENUM('active','inactive') NOT NULL DEFAULT 'active',
 created_at DATETIME DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 FOREIGN KEY(subject_id) REFERENCES subjects(id)
) ENGINE=InnoDB;
CREATE TABLE teacher_classes (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, teacher_id BIGINT UNSIGNED NOT NULL, class_id BIGINT UNSIGNED NOT NULL,
 day_of_week TINYINT UNSIGNED NOT NULL, start_time TIME NOT NULL, end_time TIME NOT NULL,
 status ENUM('active','inactive') NOT NULL DEFAULT 'active',
 created_at DATETIME DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 FOREIGN KEY(teacher_id) REFERENCES teachers(id), FOREIGN KEY(class_id) REFERENCES classes(id),
 INDEX idx_teacher_schedule(teacher_id,day_of_week,start_time,end_time)
) ENGINE=InnoDB;
CREATE TABLE student_classes (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, student_id BIGINT UNSIGNED NOT NULL, class_id BIGINT UNSIGNED NOT NULL,
 assigned_at DATETIME DEFAULT CURRENT_TIMESTAMP, status ENUM('active','inactive') NOT NULL DEFAULT 'active',
 UNIQUE KEY uq_student_class(student_id,class_id),
 FOREIGN KEY(student_id) REFERENCES students(id), FOREIGN KEY(class_id) REFERENCES classes(id)
) ENGINE=InnoDB;
CREATE TABLE fee_structures (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, class_id BIGINT UNSIGNED NOT NULL, monthly_fee DECIMAL(10,2) NOT NULL,
 effective_from DATE NOT NULL, effective_to DATE NULL,
 status ENUM('active','inactive') NOT NULL DEFAULT 'active', created_by BIGINT UNSIGNED NULL,
 created_at DATETIME DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 FOREIGN KEY(class_id) REFERENCES classes(id), FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB;
CREATE TABLE fee_payments (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, student_id BIGINT UNSIGNED NOT NULL, fee_month DATE NOT NULL,
 amount DECIMAL(10,2) NOT NULL, payment_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 payment_method ENUM('cash','upi','bank_transfer','other') NOT NULL, collected_by BIGINT UNSIGNED NOT NULL,
 receipt_number VARCHAR(50) NOT NULL UNIQUE, notes TEXT,
 UNIQUE KEY uq_student_month(student_id,fee_month),
 FOREIGN KEY(student_id) REFERENCES students(id), FOREIGN KEY(collected_by) REFERENCES users(id)
) ENGINE=InnoDB;
CREATE TABLE receipts (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, fee_payment_id BIGINT UNSIGNED NOT NULL UNIQUE,
 receipt_number VARCHAR(50) NOT NULL UNIQUE, generated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(fee_payment_id) REFERENCES fee_payments(id) ON DELETE CASCADE
) ENGINE=InnoDB;
CREATE TABLE homework (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, class_id BIGINT UNSIGNED NOT NULL, teacher_id BIGINT UNSIGNED NOT NULL,
 subject_id BIGINT UNSIGNED NOT NULL, homework_date DATE NOT NULL, due_date DATE NOT NULL,
 title VARCHAR(255) NOT NULL, description TEXT NOT NULL,
 created_at DATETIME DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 FOREIGN KEY(class_id) REFERENCES classes(id), FOREIGN KEY(teacher_id) REFERENCES teachers(id), FOREIGN KEY(subject_id) REFERENCES subjects(id)
) ENGINE=InnoDB;
CREATE TABLE classwork (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, class_id BIGINT UNSIGNED NOT NULL, teacher_id BIGINT UNSIGNED NOT NULL,
 subject_id BIGINT UNSIGNED NOT NULL, work_date DATE NOT NULL, topic VARCHAR(255) NOT NULL,
 description TEXT NOT NULL, notes TEXT,
 created_at DATETIME DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 FOREIGN KEY(class_id) REFERENCES classes(id), FOREIGN KEY(teacher_id) REFERENCES teachers(id), FOREIGN KEY(subject_id) REFERENCES subjects(id)
) ENGINE=InnoDB;
CREATE TABLE audit_logs (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, actor_user_id BIGINT UNSIGNED NULL, action VARCHAR(100) NOT NULL,
 entity_type VARCHAR(100) NOT NULL, entity_id BIGINT UNSIGNED NULL, description TEXT,
 created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(actor_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB;


-- Attendance: one record per student, course and calendar date.
CREATE TABLE IF NOT EXISTS attendance (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 student_id BIGINT UNSIGNED NOT NULL,
 class_id BIGINT UNSIGNED NOT NULL,
 attendance_date DATE NOT NULL,
 status ENUM('present','absent') NOT NULL,
 marked_by BIGINT UNSIGNED NOT NULL,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 UNIQUE KEY uq_attendance_student_class_date (student_id,class_id,attendance_date),
 CONSTRAINT fk_attendance_student FOREIGN KEY (student_id) REFERENCES students(id),
 CONSTRAINT fk_attendance_class FOREIGN KEY (class_id) REFERENCES classes(id),
 CONSTRAINT fk_attendance_marker FOREIGN KEY (marked_by) REFERENCES users(id)
);


CREATE TABLE IF NOT EXISTS enquiries (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 name VARCHAR(150) NOT NULL,
 phone VARCHAR(30) NOT NULL,
 message TEXT NOT NULL,
 status ENUM('new','read','resolved') NOT NULL DEFAULT 'new',
 admin_note TEXT NULL,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 INDEX idx_enquiries_status_created(status,created_at)
) ENGINE=InnoDB;


CREATE TABLE IF NOT EXISTS complaints (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 student_id BIGINT UNSIGNED NOT NULL,
 class_id BIGINT UNSIGNED NULL,
 complaint_date DATE NOT NULL,
 subject VARCHAR(255) NOT NULL,
 description TEXT NOT NULL,
 status ENUM('open','in_progress','resolved') NOT NULL DEFAULT 'open',
 admin_note TEXT NULL,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 FOREIGN KEY(student_id) REFERENCES students(id) ON DELETE CASCADE,
 FOREIGN KEY(class_id) REFERENCES classes(id) ON DELETE SET NULL,
 INDEX idx_complaints_student_date(student_id,complaint_date),
 INDEX idx_complaints_status(status),
 INDEX idx_complaints_class_id(class_id)
);
